server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: id
            client-secret: secret
          github:
            client-id: id
            client-secret: secret
          facebook:
            client-id: id
            client-secret: secret

logging:
  level:
    com.example.springsecuritytutorial: trace

