server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
#    org.springframework.jdbc: INFO

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: true