server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
          github:
            client-id: id
            client-secret: secret
          facebook:
            client-id: id
            client-secret: secret
logging:
  level:
    org.springframework.security: INFO
    org.springframework.jdbc: INFO