server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.jdbc: INFO
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.18:3306/test
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true