server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://192.168.0.18:3306/test
    username: test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    com.example.springsecuritytutorial: trace
